#
language: python
python: "3.6"
dist: xenial # trusty fails with weird FileNotFoundError in ExportContainerTask

sudo:  required
services:
    - docker

install:
  - sudo pip install pipenv

jobs:
  include:
#    - stage: build
#      script:
#        - ./exaslct build --flavor-path flavors/standard-EXASOL-6.1.0 --docker-repository-name docker.io/tkilias/script-language-container
    - stage: test
      script:
        - ./exaslct run-db-test --flavor-path flavors/standard-EXASOL-6.1.0 --generic-language-test=python --test-folder=python --docker-repository-name docker.io/tkilias/script-language-container
    - script:
        - ./exaslct run-db-test --flavor-path flavors/standard-EXASOL-6.1.0 --generic-language-test=java --test-folder=java --docker-repository-name docker.io/tkilias/script-language-container
    - script:
        - ./exaslct run-db-test --flavor-path flavors/standard-EXASOL-6.1.0 --generic-language-test=r --test-folder=r --docker-repository-name docker.io/tkilias/script-language-container
    - script:
        - ./exaslct run-db-test --flavor-path flavors/standard-EXASOL-6.1.0 --generic-language-test=python3 --test-folder=python3 --docker-repository-name docker.io/tkilias/script-language-container
    - script:
        - ./exaslct run-db-test --flavor-path flavors/standard-EXASOL-6.1.0 --test-folder=standard-flavor --docker-repository-name docker.io/tkilias/script-language-container
stages:
#  - build
  - test